# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx

julia:
  - 0.6
  - 0.7
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly

## uncomment the following lines to override the default test script
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'VERSION < v"0.7-" && exit(); using Pkg; Pkg.activate("."); Pkg.add(PackageSpec(name="PkgDev", rev="kc/07")); Pkg.build("PackageManagerCLI"); Pkg.test("PackageManagerCLI"; coverage=true)'
  - julia -e 'VERSION >= v"0.7-" && exit(); Pkg.clone(pwd()); Pkg.build("PackageManagerCLI"); Pkg.test("PackageManagerCLI"; coverage=true)'
