#!/usr/bin/env julia
module jpm
using ArgParse
using PackageManagerCLI

const PWD = pwd()
const default_pkgname = first(splitext(basename(PWD)))
function add_nondefault_settings()
  sdef = PackageManagerCLI.jpm_cli_settings_default
  @add_arg_table sdef["develop"] begin
    "pkg"
      help = "Package to generate"
      required = false
      default = default_pkgname
    "path"
      help = "Path for generated package"
      required = false
      default = PWD
    "--license"
      help = "License to give new package"
      arg_type = AbstractString
      default = "MIT"
      required = false
    "--force"
      help = "Force overwriting files in [path]"
      action = :store_true
  end
  @add_arg_table sdef["link"] begin
    "destpkg"
      help = "Destination package name"
      required = false
      default = default_pkgname
    "srcpath"
      help = "Source folder for link"
      required = false
      default = PWD
  end
  @add_arg_table sdef["unlink"] begin
    "pkg"
      help = "Package to unlink"
      required = false
      default = default_pkgname
  end
  sdef
end
const s = add_nondefault_settings()

usage() = parse_args(["--help"], s)

function main()
  args = parse_args(s)
  cmd = args["%COMMAND%"]

  if cmd == nothing
    usage()
  else
    # dump(args)
    # dump(cmd)
    return exec_cmd(Val{Symbol(cmd)}, args[cmd])
  end
  return 0
end

exit(main())
end # module
